branch-defaults:
  default:
    environment: FindTheAfikoman-env
environment-defaults:
  FindTheAfikoman-env:
    branch: null
    repository: null
global:
  application_name: find-the-afikoman
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Node.js running on
    64bit Amazon Linux/4.14.1
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
